# Generated by Django 3.1.2 on 2020-11-25 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Intity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('intities_pic', models.FileField(upload_to='images')),
                ('created', models.DateField()),
                ('works', models.TextField(default='')),
                ('abstract', models.TextField(default='')),
                ('permission', models.FileField(upload_to='images')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.classification')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.region')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'intities',
            },
        ),
    ]
